### ISSUE TITLE
does not build with latest rustc

### ISSUE THREAD

**Issue by matthiaskrgr** [RustSec/cargo-audit#91] opened 2019-07-29 07:04 UTC
rustc 8b94e9e9188b65df38a5f1ae723617dc2dfb3155  (seems to also fail for rustc nightly)

````
    Checking rustsec v0.12.0
    Checking abscissa_core v0.2.0
error: `X...` range patterns are not supported
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustsec-0.12.0/src/advisory/date.rs:65:20
   |
65 |             Ok($min...$max) => (),
   |                    ^^^ help: try using the maximum value for the type: `YEAR_MIN...MAX`
...
75 |     check_date_part!("year", string, parts, 4, YEAR_MIN, YEAR_MAX);
   |     --------------------------------------------------------------- in this macro invocation

error: expected one of `)` or `,`, found `YEAR_MAX`
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustsec-0.12.0/src/advisory/date.rs:65:23
   |
65 |             Ok($min...$max) => (),
   |                       ^^^^ expected one of `)` or `,` here
...
75 |     check_date_part!("year", string, parts, 4, YEAR_MIN, YEAR_MAX);
   |     --------------------------------------------------------------- in this macro invocation

error: `X...` range patterns are not supported
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustsec-0.12.0/src/advisory/date.rs:65:20
   |
65 |             Ok($min...$max) => (),
   |                    ^^^ help: try using the maximum value for the type: `1...MAX`
...
76 |     check_date_part!("month", string, parts, 2, 1, 12);
   |     --------------------------------------------------- in this macro invocation

error: expected one of `)` or `,`, found `12`
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustsec-0.12.0/src/advisory/date.rs:65:23
   |
65 |             Ok($min...$max) => (),
   |                       ^^^^ expected one of `)` or `,` here
...
76 |     check_date_part!("month", string, parts, 2, 1, 12);
   |     --------------------------------------------------- in this macro invocation

error: `X...` range patterns are not supported
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustsec-0.12.0/src/advisory/date.rs:65:20
   |
65 |             Ok($min...$max) => (),
   |                    ^^^ help: try using the maximum value for the type: `1...MAX`
...
78 |     check_date_part!("day", string, parts, 2, 1, 31);
   |     ------------------------------------------------- in this macro invocation

error: expected one of `)` or `,`, found `31`
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustsec-0.12.0/src/advisory/date.rs:65:23
   |
65 |             Ok($min...$max) => (),
   |                       ^^^^ expected one of `)` or `,` here
...
78 |     check_date_part!("day", string, parts, 2, 1, 31);
   |     ------------------------------------------------- in this macro invocation

error: arbitrary expressions aren't allowed in patterns
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustsec-0.12.0/src/advisory/date.rs:75:58
   |
75 |     check_date_part!("year", string, parts, 4, YEAR_MIN, YEAR_MAX);
   |                                                          ^^^^^^^^
````

**Comment by tarcieri** [comment] 2019-07-29 17:39
Fixed in https://github.com/RustSec/rustsec-crate/pull/66

Will release `rustsec` 0.12.1 with this fix.

**Closed by tarcieri** 2019-07-29 17:39 UTC

**Comment by tarcieri** [comment] 2019-07-29 18:42
It's out, and I've confirmed that `cargo-audit` now installs on nightly

**Comment by ramosbugs** [comment] 2019-07-30 07:01
Still seems to be failing on latest nightly on Travis CI: https://travis-ci.org/ramosbugs/oauth2-rs/jobs/565330315 (https://github.com/ramosbugs/oauth2-rs/blob/master/.travis.yml)

**Comment by tarcieri** [comment] 2019-07-30 13:40
That's a new error:

```
error: `X..=` range patterns are not supported
```

The previous error was about the deprecated `...` syntax.

It appears to be this upstream bug:

https://github.com/rust-lang/rust/issues/63115
